# Generated by Django 4.2.30 on 2026-08-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
